In [7]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

Problem: Predicting Stock Prices: Develop a time series prediction model to
forecast stock prices.

Understanding the data

In [8]:
df=pd.read_csv("/content/drive/MyDrive/Arnav Python MLLAB/stock_price_with_price_column (1).csv")
df.head()

         Date Stock    Open    High     Low   Close   Volume       Price
0  2020-01-01  AAPL  173.80  174.75  173.68  174.43  8204212  174.286667
1  2020-01-02  AAPL  176.01  177.59  174.07  177.55  2766891  176.403333
2  2020-01-03  AAPL  177.57  178.37  176.62  176.71  5721339  177.233333
3  2020-01-06  AAPL  176.01  177.58  171.33  171.73  9242680  173.546667
4  2020-01-07  AAPL  171.85  172.20  170.69  170.82  4416664  171.236667

In [9]:
df.shape
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6525 entries, 0 to 6524
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6525 non-null   object
 1   Stock   6525 non-null   object
 2   Open    6525 non-null   float64
 3   High    6525 non-null   float64
 4   Low     6525 non-null   float64
 5   Close   6525 non-null   float64
 6   Volume  6525 non-null   int64
 7   Price   6525 non-null   float64
dtypes: float64(5), int64(1), object(2)
memory usage: 407.9+ KB

DATA PREPROCESSING

In [10]:
le=LabelEncoder()
for col in df.columns:
  if df[col].dtype == 'object':
    df[col]=le.fit_transform(df[col])
df.head()

   Date  Stock    Open    High     Low   Close   Volume       Price
0     0      0  173.80  174.75  173.68  174.43  8204212  174.286667
1     1      0  176.01  177.59  174.07  177.55  2766891  176.403333
2     2      0  177.57  178.37  176.62  176.71  5721339  177.233333
3     3      0  176.01  177.58  171.33  171.73  9242680  173.546667
4     4      0  171.85  172.20  170.69  170.82  4416664  171.236667

TRAIN TEST

In [11]:
X=df.drop('Price',axis=1)
y=df['Price']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

LINEAR REGRESSION

In [12]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

PREDCTIONS

In [13]:
y_pred=model.predict(X_test)

EVALUATION

In [14]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared error: ",mse)
print("R2 Score: ",r2)

Mean Squared error:  8.492510183993655e-26
R2 Score:  1.0